### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by HalluxX** [arecvlohe/rbc-with-dnd-starter#2]
Having issues getting this is run. The following errors are generated when starting.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rbc@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rbc@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by HalluxX** [comment]
Sorry, after uninstalling node and all the npm directories and do a fresh install I was able to get it up and running. Sorry for not trying that before posting an issue. I do have further questions about possible expansion on this if you would be open to chat. Thank you

**Comment by arecvlohe** [comment]
@HalluxX sure thing! Let me know what you think about improving this
